services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FIREBASE_CONFIGURATION_PATH: credentials.json
      FIREBASE_DATABASE_URL: https://hydropnocis-demo-default-rtdb.europe-west1.firebasedatabase.app/
    ports:
      - "8080:8080"